declare module 'source-map-loader'
declare module 'webpack-bundle-analyzer'
declare module 'rimraf'
declare module 'koa-static'
declare module 'webpackbar'
// declare module '@vitejs/plugin-legacy'
// declare module '@vitejs/plugin-vue'
// declare module '@vitejs/plugin-react-refresh'